'use strict';

// Builds the static site's stage bundle from the real Node catalog.
//
// The Node modules use `Buffer` for Base64/Hex. Those specific bodies are
// rewritten to browser-safe equivalents (TextEncoder/TextDecoder + btoa/atob)
// so the live demo on the site runs the *same* logic as the package.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const WEB = path.join(__dirname, '..', 'web');
const ASSETS = path.join(WEB, 'assets');

const stages = require('../src/modules');

const NODE_B64_ENC = "Buffer.from(String(value), 'utf8').toString('base64')";
const NODE_B64_DEC = "Buffer.from(String(value), 'base64').toString('utf8')";
const NODE_HEX_ENC = "Buffer.from(String(value), 'utf8').toString('hex')";
const NODE_HEX_DEC = "Buffer.from(String(value), 'hex').toString('utf8')";

const WEB_B64_ENC =
  "((s) => { const bytes = new TextEncoder().encode(String(s)); let bin = ''; bytes.forEach((b) => { bin += String.fromCharCode(b); }); return btoa(bin); })(value)";
const WEB_B64_DEC =
  "((s) => { const bin = atob(String(s)); const bytes = Uint8Array.from(bin, (c) => c.charCodeAt(0)); return new TextDecoder().decode(bytes); })(value)";
const WEB_HEX_ENC =
  "Array.from(new TextEncoder().encode(String(value))).map((b) => b.toString(16).padStart(2, '0')).join('')";
const WEB_HEX_DEC =
  "((s) => { const bytes = Uint8Array.from(String(s).match(/.{1,2}/g) || [], (h) => parseInt(h, 16)); return new TextDecoder().decode(bytes); })(value)";

function toBrowserBody(body) {
  return body
    .split(NODE_B64_ENC).join(WEB_B64_ENC)
    .split(NODE_B64_DEC).join(WEB_B64_DEC)
    .split(NODE_HEX_ENC).join(WEB_HEX_ENC)
    .split(NODE_HEX_DEC).join(WEB_HEX_DEC);
}

// Group stages into coarse categories so the site can show useful stats.
function categoryOf(name) {
  const n = name.toLowerCase();
  if (n.startsWith('replace ')) return 'Replace';
  if (n.startsWith('caesar')) return 'Cipher';
  if (n.startsWith('prefix') || n.startsWith('suffix')) return 'Affix';
  if (n.startsWith('pad ')) return 'Pad';
  if (n.startsWith('truncate')) return 'Truncate';
  if (n.startsWith('repeat')) return 'Repeat';
  if (n.startsWith('indent')) return 'Indent';
  if (n.startsWith('wrap')) return 'Wrap';
  if (n.startsWith('mask')) return 'Mask';
  if (n.startsWith('slug')) return 'Slug';
  if (n.startsWith('whitespace')) return 'Whitespace';
  if (n.startsWith('bullet')) return 'Lines';
  if (n.includes('lines') || n.startsWith('drop ') || n.startsWith('take ')) return 'Lines';
  if (n.includes('case')) return 'Case';
  if (
    n.includes('base64') ||
    n.includes('hex') ||
    n.includes('binary') ||
    n.includes('uri') ||
    n.includes('html') ||
    n.includes('atbash')
  )
    return 'Encoding';
  if (n.startsWith('interleave') || n.startsWith('mirror')) return 'Compose';
  return 'Other';
}

const data = stages.map((stage) => ({
  id: stage.id,
  name: stage.name,
  description: stage.description,
  category: categoryOf(stage.name),
  run: toBrowserBody(stage.run.toString()),
}));

const counts = {};
for (const s of data) counts[s.category] = (counts[s.category] || 0) + 1;

fs.mkdirSync(ASSETS, { recursive: true });

const header =
  '/* Auto-generated by scripts/build-web.js. Do not edit by hand. */\n' +
  '/* ' + data.length + ' stages, mirrored from the Node catalog for the browser. */\n';

fs.writeFileSync(
  path.join(ASSETS, 'stages.js'),
  header + 'window.STAGEKIT_STAGES = ' + JSON.stringify(data, null, 0) + ';\n',
  'utf8'
);

fs.writeFileSync(
  path.join(ASSETS, 'meta.json'),
  JSON.stringify(
    {
      count: data.length,
      categories: Object.keys(counts)
        .sort()
        .map((k) => ({ name: k, count: counts[k] })),
      generatedAt: new Date().toISOString(),
    },
    null,
    2
  ) + '\n',
  'utf8'
);

// Cache-bust the local assets. GitHub Pages serves them with a 10-minute
// cache, so a fresh deploy could pair new HTML with a stale stylesheet and
// render an unstyled page. Stamping a content hash into the HTML forces the
// browser to fetch the new files immediately.
const hash = crypto.createHash('sha1');
for (const f of ['styles.css', 'app.js', 'stages.js']) {
  hash.update(fs.readFileSync(path.join(ASSETS, f)));
}
const version = hash.digest('hex').slice(0, 10);

const indexPath = path.join(WEB, 'index.html');
const index = fs
  .readFileSync(indexPath, 'utf8')
  .replace(/assets\/styles\.css(\?v=[^"']*)?/g, 'assets/styles.css?v=' + version)
  .replace(/assets\/app\.js(\?v=[^"']*)?/g, 'assets/app.js?v=' + version)
  .replace(/assets\/stages\.js(\?v=[^"']*)?/g, 'assets/stages.js?v=' + version);
fs.writeFileSync(indexPath, index, 'utf8');

console.log('web bundle: ' + data.length + ' stages -> web/assets/stages.js');
console.log('categories: ' + Object.keys(counts).length);
console.log('asset version: ' + version);
